[package]
name = "robin"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "File utility CLI (file hashes, file info, directory trees)"

[dependencies]
hash-utils = { path = "../hash-utils" }
clap.workspace = true
clap_complete.workspace = true
colored.workspace = true
thiserror.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true

[lints]
workspace = true
