[package]
name = "rcli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "rcli"
test = false
bench = false
[dependencies]
clap = { version = "^4.4.11", features = ["derive", "cargo"] }
