[package]
name = "study"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Study tool CLI (file operations, string utils)"

[dependencies]
clap.workspace = true
clap_complete.workspace = true
md-5.workspace = true
rand.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true

[lints]
workspace = true

