[package]
name = "study"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.10.5"
clap = { version = "^4.4.11", features = ["derive", "cargo"] }
rand = "0.8.5"