[workspace]
resolver = "2"
members = [
    "basic",
    "counter",
    "dante",
    "fade",
    "find_file",
    "guess",
    "mini",
    "mini_web",
    "minigrep",
    "rcli",
    "ruanmei",
    "seele",
    "study",
    "web_app",
]
