[workspace]
resolver = "2"
members = [
    "basic",
    "counter",
    "dante",
    "fade",
    "find_file",
    "guess",
    "mini",
    "mini_web",
    "minigrep",
    "rcli",
    "ruanmei",
    "seele",
    "study",
    "web_app",
]

[workspace.package]
edition = "2024"
authors = ["yzqdev"]
version = "0.1.0"

[workspace.dependencies]
clap = { version = "4.5.30", features = ["derive", "cargo"] }
clap_complete = "4.5.30"
anyhow = "1.0.80"
thiserror = "2.0.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
serde_cbor = "0.11.2"
colored = "3.0.0"
regex = "1"
glob = "0.3.2"
chrono = "0.4"
md-5 = "0.10.6"
rand = "0.8.5"
crossterm = "0.28.1"
ratatui = "0.29.0"
axum = "0.8.1"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = { version = "0.12.4", features = ["json"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
lazy_static = "1.4"
mini-redis = "0.4"
# dev-dependencies
assert_cmd = "2.0.0"
predicates = "3.0.0"
tower = "0.5"
http-body-util = "0.1"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"

[profile.release]
strip = true
lto = "thin"
