# 使用 PowerShell 替代 sh:
set shell := ["pwsh"," –noprofile", "-c"]
default:
  @just --list

hello:
  Write-Host "Hello, world!"
a:
  echo 'This is a recipe!'
study :
	cargo run   

build target:
  @echo "Building {{target}}…"