[package]
name = "find_file"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "File finder CLI (by pattern, size, recency, emptiness)"

[dependencies]
clap.workspace = true
clap_complete.workspace = true
glob.workspace = true
thiserror.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true

[lints]
workspace = true

