[package]
name = "cli"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "cli"
[dependencies]
clap={version = "*",features = ["derive","cargo"]}
reqwest={version = "*"}