[package]
name = "nero"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "nero"
path = "src/main.rs"
[dependencies]
clap = "4.4.6"
common = { path = "../common" }
