[package]
name = "minigrep"
version = "0.1.0"
authors = ["Subhojit Paul <subhojitpaul21@gmail.com>"]
edition = "2024"
[dependencies]
colored = "3.0.0"
regex = "1"
clap = { version = "^4.5.4", features = ["derive", "cargo"] }