[package]
name = "minigrep"
version.workspace = true
edition.workspace = true
authors = ["Subhojit Paul <subhojitpaul21@gmail.com>"]
description = "A fast and simple grep-like text search tool"

[dependencies]
colored.workspace = true
regex.workspace = true
clap.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true

[lints]
workspace = true
