[package]
name = "dante"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "A versatile CLI tool (greet, calc, echo, now)"

[dependencies]
clap.workspace = true
clap_complete.workspace = true
chrono.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true

[lints]
workspace = true

